# Generated by Django 6.0.1 on 2026-01-20 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Вид работ')),
                ('date', models.DateField(verbose_name='Дата')),
                ('mileage', models.IntegerField(verbose_name='Пробег (км)')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.motorcycle', verbose_name='Мотоцикл')),
            ],
        ),
    ]
